apiVersion : apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: webappspacegame.azurecr.io/web:latest
          ports:
          - containerPort: 5000
          env:
          - name: ASPNETCORE_URLS
            value: "http://0.0.0.0:5000"
      imagePullSecrets:
        - name: secret
---
apiVersion : apps/v1
kind: Deployment
metadata:
  name: leaderboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leaderboard
  template:
    metadata:
      labels:
        app: leaderboard
    spec:
      containers:
        - name: leaderboard
          image: webappspacegame.azurecr.io/leaderboard:latest
          ports:
          - containerPort: 8080
          env:
          - name: ASPNETCORE_URLS
            value: "http://0.0.0.0:8080"
      imagePullSecrets:
        - name: secret











